name: Build and Release

on:
  push:
    tags:
      - "*" # Run on all tags pushed to the repository

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify a valid Node.js version

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend # Navigate to frontend directory

      - name: Build with esbuild
        run: npm run build # Adjust based on your build script
        working-directory: ./frontend # Navigate to frontend directory

      - name: Get Latest Release ID
        id: get_release_id
        run: |
          echo ${GITHUB_REPOSITORY}
          echo ${{ github.ref }}
          RESPONSE=$(curl -s -X GET \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${{ github.ref }}")
          echo $RELEASE
          RELEASE_ID=$(echo $RESPONSE | jq -r '.id')
          echo "RELEASE_ID"
          echo $RELEASE_ID
          UPLOAD_URL=$(echo $RESPONSE | jq -r '.upload_url')
          echo "UPLOAD_URL"
          echo $UPLOAD_URL
          if [ "$RELEASE_ID" = "null" ]; then
            echo "Release with tag '${{ github.ref }}' not found."
            exit 1
          fi
          echo "::set-output name=release_id::$RELEASE_ID"
          echo "::set-output name=upload_url::$UPLOAD_URL"

      - name: Update Release
        if: steps.get_release_id.outputs.release_id != null
        run: |
          RELEASE_ID="${{ steps.get_release_id.outputs.release_id }}"
          RESPONSE=$(curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}" \
            -d "{\"tag_name\": \"${{ github.ref }}\", \"name\": \"Release ${{ github.ref }}\", \"draft\": false, \"prerelease\": false}")

      - name: Upload Release Asset
        if: steps.get_release_id.outputs.release_id != null
        run: |
          RELEASE_ID="${{ steps.get_release_id.outputs.release_id }}"
          UPLOAD_URL="${{ steps.get_release_id.outputs.upload_url }}"
          echo "Uploading release asset..."
          echo "Release ID: $RELEASE_ID"
          echo "Upload URL: $UPLOAD_URL"
          # Add your asset upload command here using the RELEASE_ID and UPLOAD_URL
