name: Build and Release

on:
  push:
    tags:
      - '*'  # Run on all tags pushed to the repository

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use Node.js version 16
          # You can specify any Node.js version supported by actions/setup-node

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend  # Navigate to frontend directory

      - name: Build with esbuild
        run: npm run build  # Adjust based on your build script
        working-directory: ./frontend  # Navigate to frontend directory

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          update: true  # Update existing release if it exists

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/raffle-tool
          asset_name: raffle-tool-${{ github.ref }}.zip
          asset_content_type: application/zip
